InfoTrackSearchTracker/Models/ErrorViewModel.cs
namespace InfoTrackSearchTracker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InfoTrackSearchTracker/Models/SearchEngine.cs
namespace InfoTrackSearchTracker.Models
{
    public enum SearchEngine
    {
        Google,
        Bing,
    }
}

InfoTrackSearchTracker/Models/SearchTrack/SearchTrackViewModel.cs
using System.ComponentModel;
using System.Reflection.Metadata.Ecma335;

namespace InfoTrackSearchTracker.Models.SearchTrack
{
    public class SearchTrackViewModel
    {
        [DisplayName("Enter phrase")]
        public string SearchString { get; set; } = "";
        [DisplayName("Enter URL to search for")]
        public string? URLSearch { get; set; }
        public SearchEngine SearchEngine { get; set; } = SearchEngine.Google;
        public int NumberOfOccurrence { get; set; }
        public string? Postions { get; set; }
    }
}

InfoTrackSearchTracker/Controllers/HomeController.cs
using InfoTrackSearchTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InfoTrackSearchTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InfoTrackSearchTracker/Controllers/SearchTrack/SearchTrackController.cs
using InfoTrackSearchTracker.Models.SearchTrack;
using InfoTrackSearchTracker.Services;
using InfoTrackSearchTracker.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InfoTrackSearchTracker.Controllers.SearchTrack
{
    public class SearchTrackController : Controller
    {
        ISearchTrackServices _services;
        public SearchTrackController(ISearchTrackServices services)
        {
            _services = services;
        }
        // GET: SearchTrackController
        public async Task<ActionResult> Index()
        {
            var model = await _services.GetSearchTrackViewModel();
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Index(SearchTrackViewModel input)
        {
            if (input.SearchString.IsURL())
            {
                ModelState.AddModelError("SearchString", "Cannot enter a URL in a phrase");
            }
            if (!input.URLSearch.IsURL() && !string.IsNullOrWhiteSpace(input.URLSearch))
            {
                ModelState.AddModelError("URLSearch", "Please enter a valid URL to search for");
            }
            try
            {
                var model = await _services.GetCustomSearchTrack(input);
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("SearchString", ex.Message);
            }
            return RedirectToAction("Index");
        }
    }
}

InfoTrackSearchTracker/Views/Home/Index.cshtml
@using InfoTrackSearchTracker.Utilities
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        The CEO from InfoTrack is very interested in SEO and how this can improve Sales. Every morning he searches
        the keyword “land registry searches” in Google and counts down to see where and how many times their
        company, www.infotrack.co.uk sits on the list. Seeing the CEO do this every day, a smart software developer
        at InfoTrack decides to write a small application for him that will automatically perform this operation and return
        the result to the screen.
    </p>
    <p>
        The following is my solution.
    </p>
    <div class="col-sm-6 small-margin-bottom" style="text-align:center">
    </div>
    <div class="align-content-center">
        <a class="btn btn-primary" asp-controller="SearchTrack" asp-action="Index">Begin</a>
    </div>
</div>

InfoTrackSearchTracker/Views/SearchTrack/Index.cshtml
@using InfoTrackSearchTracker.Utilities
@model InfoTrackSearchTracker.Models.SearchTrack.SearchTrackViewModel
@{
    ViewData["Title"] = "Search Track";
}

<div>
    <h1 class="display-4 text-center">Search Track</h1>
    <div class="text-center">
        <p>
            Search: "@Model.SearchString"
        </p>
        <p>
            Search Engine: "@Model.SearchEngine"
        </p>
    </div>
    <div class="text-center">
        <p>
            "@Model.URLSearch" has occurred @Model.NumberOfOccurrence time(s) and found in postion(s): @Model.Postions
            out of 100 search results
        </p>
    </div>
    <hr />
    <p>
        Want to see how many times certain site appears in a custom search?
    </p>
    <form method="post">
        <div asp-validation-summary="All"></div>
        <div class="border p-3 mt-4">
            <div class="mb-3">
                <label asp-for="SearchString" class="p-0"></label>
                <input asp-for="SearchString" class="form-control"/>
                <span asp-validation-for="SearchString" class="text-bg-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="URLSearch" class="p-0"></label>
                <input asp-for="URLSearch" class="form-control" />
                <span asp-validation-for="URLSearch" class="text-bg-danger"></span>
            </div>
            <div class="mb-3">
            <select asp-for="SearchEngine" asp-items="Html.GetEnumSelectList<SearchEngine>()" class="form-control"></select>
            <span asp-validation-for="SearchEngine" class="text-bg-danger"></span>
            </div>
        </div>
        <div class="col-12">
                <button type="submit" class="btn btn-primary form-control">Search</button>
        </div>
    </form>
</div>

InfoTrackSearchTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Info Track SEO Tool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InfoTrackSearchTracker.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InfoTrack SEO Tool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="SearchTrack" asp-action="Index">Search track</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-suit-heart"></i> by Karl Sartorio
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>